services:
  # MongoDB Database
  - type: pserv
    name: logms-mongodb
    env: docker
    plan: starter
    image: mongo:7.0
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 1
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: logms
      - key: MONGO_INITDB_ROOT_PASSWORD
        generateValue: true
      - key: MONGO_INITDB_DATABASE
        value: logms

  # Unified Backend + Frontend Service
  - type: web
    name: logms-app
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromService:
          name: logms-mongodb
          type: pserv
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: APP_ADMIN_EMAIL
        value: admin@example.com
      - key: APP_ADMIN_PASSWORD
        generateValue: true
      - key: DEFAULT_TENANT
        value: default
      - key: SYSLOG_UDP_PORT
        value: 5140
      - key: SYSLOG_TCP_PORT
        value: 5140
      - key: RESEND_API_KEY
        sync: false
      - key: ALERT_EMAIL_FROM
        sync: false
      - key: ALERT_EMAIL_TO
        sync: false
